[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_todo_list = "7XSt7wdjFJnyRCAPo9sVTqv8QWFxcNUU3G73Vqmq4wjZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nikhil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
